name: hyloader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  oauth2: ^2.0.5
  url_launcher: ^6.3.2
  hyapi:
    path:
      ./packages/hyapi
  wharf_flutter:
    path:
      ./packages/wharf_flutter
  path_provider: ^2.1.5
  process_run: ^1.2.4
  flutter_riverpod: ^3.2.0
  riverpod_annotation: ^4.0.1

flutter:
  uses-material-design: true

dev_dependencies:
  riverpod_generator: ^4.0.1
  build_runner: ^2.10.5

dependency_overrides:
  analyzer_buffer: ^0.3.0
  analyzer: ^9.0.0