name: hyloader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  oauth2: ^2.0.5
  url_launcher: ^6.3.2
  hyapi:
    path:
      ./packages/hyapi
  wharf:
    path:
      ./packages/wharf
  path_provider: ^2.1.5

dev_dependesncies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
