[package]
name = "wharf_flutter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
wharf = { git = "https://github.com/EricApostal/scratch-io", version = "0.1.0" }
quote = "1.0.43"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
