[package]
name = "wharf_bridge"
version = "0.1.0"
edition = "2021"

[lib]
name = "wharf"
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.10.0"
wharf = { path = "../vendor/scratch-io/wharf", version = "0.1.0" }


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
